
export const LOAD_SPREAD_DATA_SUCCESS = 'LOAD_SPREAD_DATA_SUCCESS';
export const UPDATE_SPREAD_DATA_SUCCESS = 'UPDATE_SPREAD_DATA_SUCCESS';
export const UPDATE_SPREAD_DEFINITION = 'UPDATE_SPREAD_DEFINITION';
export const UPDATE_SPREAD_DATA = 'UPDATE_SPREAD_DATA';
export const UPDATE_CELL_DATA = 'UPDATE_CELL_DATA';
export const UPDATE_HEADER_CELL_DATA = 'UPDATE_HEADER_CELL_DATA';

